### ISSUE TITLE
logo for build it bigger

### ISSUE THREAD

**Issue by hafizahmmed** [fjoglar/build-it-bigger#1]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![build-it-bigger-01](https://user-images.githubusercontent.com/38810169/40250665-d15858f4-5af8-11e8-8642-84a41b3b6b0d.jpg)

**Comment by felipejoglar** [comment]
Thanks @hafizahmmed, I appreciate your interest, but this is just an academic project and I will keep making the logos myself until the end of the course.

Thanks anyway! :wink:
